services:
  data-tree-api:
    container_name: data-tree-api
    image: data-tree-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    command: >
      sh -c "bun install && bun run dev"
